apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: la1o3ilxn-nodejs
  janus-idp.io/tekton: la1o3ilxn-nodejs
  backstage.io/kubernetes-id: la1o3ilxn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: la1o3ilxn-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
