apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: la1o3ilxn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: la1o3ilxn-nodejs 
  name: la1o3ilxn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: la1o3ilxn-nodejs 
